//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRandomizer.Generators.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheRandomizer.Generators.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Grammar xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:type=&quot;AssignmentGrammar&quot;&gt;
        ///	&lt;name&gt;Dwarven Names (AD&amp;amp;D)&lt;/name&gt;
        ///	&lt;author&gt;Lance Boudreaux&lt;/author&gt;
        ///	&lt;description&gt;A dwarven name generator based on AD&amp;amp;D.&lt;/description&gt;
        ///	&lt;category&gt;Name&lt;/category&gt;
        ///	&lt;genre&gt;Fantasy&lt;/genre&gt;
        ///	&lt;system&gt;AD&amp;amp;D&lt;/system&gt;
        ///	&lt;version&gt;1.1&lt;/version&gt;
        ///	&lt;parameters&gt;
        ///	    &lt;parameter name=&quot;Gender&quot; display=&quot;Gender&quot; type=&quot;List&quot; valueType=&quot;Label&quot;&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ADnD_Dwarf_Names_rnd {
            get {
                return ResourceManager.GetString("ADnD_Dwarf_Names_rnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Grammar xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///		 xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///		 xsi:type=&quot;PhonotacticsGrammar&quot;&gt;
        ///  &lt;name&gt;Test&lt;/name&gt;
        ///  &lt;author&gt;Lance Boudreaux&lt;/author&gt;
        ///  &lt;description&gt;Test Description&lt;/description&gt;
        ///  &lt;category&gt;Test&lt;/category&gt;
        ///  &lt;parameters /&gt;
        ///  &lt;supportsMaxLength&gt;false&lt;/supportsMaxLength&gt;
        ///  &lt;case&gt;Proper&lt;/case&gt;
        ///	&lt;!--&lt;definitions&gt;
        ///		&lt;item key=&quot;Test&quot; delimiter=&quot;,&quot;&gt;A,B,C,D&lt;/item&gt;
        ///	&lt;/definitions&gt;--&gt;
        ///  &lt;definitions&gt;
        ///    &lt;item  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phonotactics_example_rnd {
            get {
                return ResourceManager.GetString("phonotactics_example_rnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Grammar xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///		 xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///		 xsi:type=&quot;TableGrammar&quot;&gt;
        ///	&lt;name&gt;Town Generator (D&amp;amp;D 3e)&lt;/name&gt;
        ///	&lt;author&gt;Lance Boudreaux&lt;/author&gt;
        ///	&lt;description&gt;A town generator based on the D&amp;amp;D 3e DMG.&lt;/description&gt;
        ///	&lt;genre&gt;Fantasy&lt;/genre&gt;
        ///	&lt;system&gt;D&amp;amp;D&lt;/system&gt;
        ///	&lt;category&gt;Environment&lt;/category&gt;
        ///	&lt;tables&gt;
        ///		&lt;table action=&quot;Random&quot; column=&quot;Roll&quot; name=&quot;Town Size&quot; delimiter=&quot;|&quot;&gt;&lt;![CDA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TownGeneration_rnd {
            get {
                return ResourceManager.GetString("TownGeneration_rnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Grammar xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///		 xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///		 xsi:type=&quot;DiceRoll&quot;&gt;
        ///	&lt;name&gt;World of Darkness Skill Check&lt;/name&gt;
        ///	&lt;author&gt;Lance Boudreaux&lt;/author&gt;
        ///	&lt;description&gt;Rolls a skill check for World of Darkness&lt;/description&gt;
        ///	&lt;category&gt;Dice Roll&lt;/category&gt;
        ///	&lt;genre&gt;Horror&lt;/genre&gt;
        ///	&lt;system&gt;World of Darkness&lt;/system&gt;
        ///	&lt;parameters&gt;
        ///		&lt;parameter name=&quot;Version&quot; display=&quot;Version&quot; type=&quot;List&quot;&gt;
        ///			&lt;option d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorldOfDarknessCheck_rnd {
            get {
                return ResourceManager.GetString("WorldOfDarknessCheck_rnd", resourceCulture);
            }
        }
    }
}
